name: CI
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26
          args: -c .golangci.yaml
