name: CI
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 1

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
